### ISSUE TITLE
Add a 'How to contribute' section to textbook!

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/ipfs-textbook#4]

**Comment by simonv3** [comment]
You could just add a contributing.md that way the readme won't be "polluted".

**Comment by RichardLitt** [comment]
Fair.

**Comment by simonv3** [comment]
Unless you see the readme making its way around without the associated contributing.md, and then it might be interesting to include it there.

**Comment by RichardLitt** [comment]
Added! I don't think it pollutes the document at the moment.
