### ISSUE TITLE
Can I host non-static content on IPFS?

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/ipfs-textbook#6]
Can I access databases from it, or will those still need to be centrally hosted?

**Comment by RichardLitt** [comment]
I dunno. For the record, if you want the answer to questions, go to https://github.com/ipfs/ipfs or ipfs/faq. This is where I will try and answer questions, and I don't know anything.

**Comment by simonv3** [comment]
Ah cool, I guess I thought this served a similar role as ipfs/faq

**Comment by RichardLitt** [comment]
Nope. This is just for me to understand. I'm going to look up and answer all of these questions, build a non-technically savvy long description.

**Comment by simonv3** [comment]
Cool, non-technical descriptions is what I want.

**Comment by simonv3** [comment]
For your reference: https://github.com/ipfs/faq/issues/16 https://github.com/ipfs/faq/issues/28

**Comment by RichardLitt** [comment]
Thanks!
